ADD_SCENE(dashboard, dashboard, Dashboard)
ADD_SCENE(dashboard, menu, Menu)
ADD_SCENE(dashboard, settings, Settings)
ADD_SCENE(dashboard, settings_lcd, SettingsLcd)
ADD_SCENE(dashboard, canbus, Canbus)
ADD_SCENE(dashboard, canbus_detail, CanbusDetail)
